---
title: "HANPP_graphs"
author: "Kaeli Mueller"
date: "10/8/2020"
output:
  html_document: default
  pdf_document: default
---

Download important packages
```{r}
#install.packages("statsr")
#install.packages("GGally")
#install.packages("bestglm")
#install.packages("lmtest")
#install.packages("normtest")
#install.packages("emmeans")
#install.packages("hrbrthemes")


library(tidyverse)
library(statsr)
library(MuMIn)
library(dplyr)
library(GGally)
library(car)
library(bestglm)
library(stats)
library(boot)
library(lmtest)
library(MASS)
library(normtest)
library(emmeans)
library(dplyr)
library(ggplot2)
library(lmtest)
library(reshape)
library(viridis)
library(hrbrthemes)
```

Import data
```{r}
cotton_pima <- read.csv("C://Users//Kaeli//Downloads//Cottonpima_FINALHANPP.csv", header = T)

hanpp_land <- read.csv("C://Users//Kaeli//Documents//HANPP//data//HANPP_general//HANPP_DataSet_LandEstimates.csv", 
                       header = TRUE)

#make dataset smaller and manageable
hanpp_land_small <- hanpp_land[1:6,]
head(hanpp_land_small)

#First try
p <- ggplot(data=hanpp_land_small, aes(x = County, y = Total.HANPP.Harvest, fill = Corn.Grain)) + 
  geom_bar(stat='identity', color = "black")
p
```
Stacked bar chart
```{r}
#make dataset smaller
hanpp_crop <- data.frame(hanpp_land_small$County, hanpp_land_small$Corn.Grain.1, hanpp_land_small$Cotton.Upland.1, hanpp_land_small$Soybeans.1, hanpp_land_small$Hardwood.1)

hanpp_crop_reshape <- melt(hanpp_crop, id =c("hanpp_land_small.County"))

head(hanpp_crop_reshape)

#rename
names(hanpp_crop_reshape)[1:3] <- c("County", "Crop", "HANPP_Harvest")

ggplot(data = hanpp_crop_reshape, aes(fill=Crop, y = HANPP_Harvest, x = County)) + geom_bar(position = "stack", stat = "identity")
```

Change legend names (by changing the factor level names in the dataframe)
```{r}
#make them into character instead of factor
hanpp_crop_reshape$Crop <- as.character(hanpp_crop_reshape$Crop)

#rename all the weird labels into readable names
hanpp_crop_reshape[hanpp_crop_reshape == "hanpp_land_small.Corn.Grain.1"] <- "Corn"
hanpp_crop_reshape[hanpp_crop_reshape == "hanpp_land_small.Cotton.Upland.1"] <- "Upland Cotton"
hanpp_crop_reshape[hanpp_crop_reshape == "hanpp_land_small.Soybeans.1"] <- "Soybeans"
hanpp_crop_reshape[hanpp_crop_reshape == "hanpp_land_small.Hardwood.1"] <- "Hardwood"

#Get rid of random new column
hanpp_crop_final <- data.frame(hanpp_crop_reshape$County, hanpp_crop_reshape$Crop, hanpp_crop_reshape$HANPP_Harvest)

#Rename variable titles
names(hanpp_crop_final)[1:3] <- c("County", "Crop", "HANPP_Harvest")

#Coerce back to factor to 're-source' new factors
hanpp_crop_final$Crop <- factor(hanpp_crop_final$Crop)

print(hanpp_crop_final)

#Plot this new stacked bar chart
ggplot(data = hanpp_crop_final, aes(fill=Crop, y = HANPP_Harvest, x = County)) + geom_bar(position = "stack", stat = "identity")
```

Customize the bar chart colors
```{r}
ggplot(data = hanpp_crop_final, aes(fill=Crop, y = HANPP_Harvest, x = County)) + geom_bar(position = "stack", stat = "identity") + scale_fill_manual(values = c("#FFD700","#663300", "#006400", "#ff0000"))
```

test data
```{r}
specie <- c(rep("sorgho" , 3) , rep("poacee" , 3) , rep("banana" , 3) , rep("triticum" , 3) )
condition <- rep(c("normal" , "stress" , "Nitrogen") , 4)
value <- abs(rnorm(12 , 0 , 15))
data <- data.frame(specie,condition,value)
```

Improve the titles and axis lables
```{r}
ggplot(data = hanpp_crop_final, aes(fill=Crop, y = HANPP_Harvest, x = County)) + geom_bar(position = "stack", stat = "identity") + scale_fill_manual(values = c("#FFD700","#663300", "#006400", "#ff0000")) +ggtitle("HANPP Harvest in Alabama Counties") + ylab("HANPP Harvest (g C/m^2/year)")
```

```{r}
#try with a single county
#read in the entire csv
hanpp_master <- read.csv("C://Users//Kaeli//Documents//HANPP//data//HANPP_general//Master_HANPP_no_units.csv", header = TRUE)
head(hanpp_master)

#filter out the county that you want
ALABAMA_AUTAUGA_2012 <- hanpp_master %>% 
  filter(State_County == "ALABAMA_AUTAUGA")
head(ALABAMA_AUTAUGA_2012)

ALABAMA_AUTAUGA_2012 <- ALABAMA_AUTAUGA_2012 %>% 
  select(Corn.Grain.2, Corn.Silage.2, Winter.Wheat.2, Spring.Wheat.Durum.2, Spring.Wheat.Excluding.Durum.2, Soybeans.2, Hay.Alfalfa.2, Cotton.Pima.2, Cotton.Upland.2, Sorghum.2, Other.Crops.2, Total.Crops.2, Hardwood.2, Softwood.2, Total.Timber.2, BLM.Grazing.2, USFS.Grazing.2, Private.Grazing.Land.2, Total.Grazing.2, X.2, Corn.Grain.8, Corn.Silage.8, Winter.Wheat.8, Spring.Wheat.Durum.8, Spring.Wheat.Excluding.Durum.8, Soybeans.8, Hay.Alfalfa.8, Cotton.Pima.8, Cotton.Upland.8, Sorghum.8, Other.Crops.8, Total.Crops.8, Hardwood.8, Softwood.8, Total.Timber.8, BLM.Grazing.8, USFS.Grazing.8, Private.Grazing.Land.8, Total.Crops.8, X.8, Corn.Grain.9, Corn.Silage.9, Winter.Wheat.9, Spring.Wheat.Durum.9, Spring.Wheat.Excluding.Durum.9, Soybeans.9, Hay.Alfalfa.9, Cotton.Pima.9, Cotton.Upland.9, Sorghum.9, Other.Crops.9, Total.Crops.9, Hardwood.9, Softwood.9, Total.Timber.9, BLM.Grazing.9, USFS.Grazing.9, Private.Grazing.Land.9, Total.Grazing.9, X.9, Corn.Grain.10, Corn.Silage.10, Winter.Wheat.10, Spring.Wheat.Durum.10, Spring.Wheat.Excluding.Durum.10, Soybeans.10, Hay.Alfalfa.10, Cotton.Pima.10, Cotton.Upland.10, Sorghum.10, Other.Crops.10, Total.Crops.10, Hardwood.10, Softwood.10, Total.Timber.10, BLM.Grazing.10, USFS.Grazing.10, Private.Grazing.Land.10, Total.Grazing.10, X.10, Corn.Grain.11, Corn.Silage.11, Winter.Wheat.11, Spring.Wheat.Durum.11, Spring.Wheat.Excluding.Durum.11, Soybeans.11, Hay.Alfalfa.11, Cotton.Pima.11, Cotton.Pima.11, Cotton.Upland.11, Sorghum.11, Other.Crops.11, Total.Crops.11, Hardwood.11, Softwood.11, Total.Timber.11, BLM.Grazing.11, USFS.Grazing.11, Private.Grazing.Land.11, Total.Crops.11, X.11)

head(ALABAMA_AUTAUGA_2012)

#X.8 = total used, X.2 = total hanpp, X.9 = unused, X.10 = above ground, X.11 = belowground

ALABAMA_AUTAUGA_2012 <- ALABAMA_AUTAUGA_2012 %>% 
  select(Corn.Grain.2, Corn.Silage.2, Winter.Wheat.2, Spring.Wheat.Durum.2, Spring.Wheat.Excluding.Durum.2, Soybeans.2, Hay.Alfalfa.2, Cotton.Pima.2, Cotton.Upland.2, Sorghum.2, Other.Crops.2, Total.Crops.2, Hardwood.2, Softwood.2, Total.Timber.2, BLM.Grazing.2, USFS.Grazing.2, Private.Grazing.Land.2, Total.Grazing.2, X.2, X.8, X.9, X.10, X.11)
head(ALABAMA_AUTAUGA_2012)

#rename the columns
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Corn.Grain.2"] <- "Corn Grain"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Corn.Silage.2"] <- "Corn Silage"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Winter.Wheat.2"] <- "Winter Wheat"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Spring.Wheat.Durum.2"] <- "Spring Wheat Dururm"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Spring.Wheat.Excluding.Durum.2"] <- "Spring Wheat Excluding Durum"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Soybeans.2"] <- "Soybeans"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Hay.Alfalfa.2"] <- "Hay Alfalfa"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Cotton.Pima.2"] <- "Cotton Pima"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Cotton.Upland.2"] <- "Cotton Upland"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Sorghum.2"] <- "Sorghum"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Other.Crops.2"] <- "Other Crops"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Total.Crops.2"] <- "Total Crops"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Hardwood.2"] <- "Hardwood"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Softwood.2"] <- "Softwood"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Total.Timber.2"] <- "Total Timber"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "BLM.Grazing.2"] <- "BLM Grazing"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "USFS.Grazing.2"] <- "USFS Grazing"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Private.Grazing.Land.2"] <- "Private Grazing Land"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "Total.Grazing.2"] <- "Total Grazing"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "X.2"] <- "Total HANPP Harvest"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "X.8"] <- "HANPP Harvest Used"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "X.9"] <- "HANPP Harvest Unused"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "X.10"] <- "HANPP Harvest Aboveground"
names(ALABAMA_AUTAUGA_2012)[names(ALABAMA_AUTAUGA_2012) == "X.11"] <- "HANPP Harvest Belowground"
head(ALABAMA_AUTAUGA_2012)

#Make a column for types of hanpp and add it


```

